/* Operating System header file(s) */
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <time.h>
#include <sys/utsname.h>


int main (int argc, char * argv [])
{
  int option;
  unsigned char ch;

  char * filename = "first-names.txt";
  char * name = "words";
  char * type = "words_t";
  FILE * in = stdin;

  struct utsname host;
  time_t now = time (NULL);

  /* Notice the program name */
  char * progname = strrchr (argv [0], '/');
  progname = ! progname ? * argv : progname + 1;

#define OPTSTRING "f:n:"
  while ((option = getopt (argc, argv, OPTSTRING)) != EOF)
    {
      switch (option)
        {
        case 'f': filename = optarg; break;
        case 'n': name = optarg; break;
	}
    }

  if (strcmp (filename, "-") && ! (in = fopen (filename, "r")))
    {
      printf ("Error: cannot open %s\n", filename);
      return 1;
    }

  uname (& host);

  printf ("/* \n");
  printf (" * This file was automatically generated by program '%s' from source file '%s'\n", progname, ! strcmp (filename, "-") ? "<stdin>" : filename);
  printf (" * on %s %*.*s\n", host . nodename, 24, 24, ctime (& now));
  printf (" *\n");
  printf (" * (C) Copyright 2018 Rocco Carbone <rocco@tecsiel.it>\n");
  printf (" *\n");
  printf (" * Please do not edit\n");
  printf (" */\n");
  printf ("\n");

  printf ("\n");
  printf ("typedef struct\n");
  printf ("{\n");
  printf ("  char * name;\n");
  printf ("\n");
  printf ("} %s;\n", type);
  printf ("\n");
  printf ("\n");

  printf ("static %s %s [] = \n", type, name);
  printf ("{\n");

  /* Read all lines from the file */
  if (in)
    {
      char line [1024];
      while (! feof (in))
	{
	  unsigned n;
	  fgets (line, sizeof (line), in);

	  n = strlen (line) - 2;
	  printf (" { \"%*.*s\" },\n", n, n, line);
	}
      fclose (in);
    }

  printf (" {  NULL }\n");
  printf ("};\n\n");

  return 0;
}
